# Generated by Django 4.2.2 on 2023-07-03 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_item_benefits_item_gemstone_item_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
