# Generated by Django 4.2.2 on 2023-07-04 15:16

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_billingaddress_city_billingaddress_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
    ]
