# Generated by Django 4.2.2 on 2023-07-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_billingaddress_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
